insert into student (id, first_name, last_name, gpa, dob, address) values (1, 'Lorene', 'Tolliday', 3.6, '2023-08-13', 'Tiantai');
insert into student (id, first_name, last_name, gpa, dob, address) values (2, 'Vincenty', 'Soigne', 2.23, '2023-03-21', 'Bektemir');
insert into student (id, first_name, last_name, gpa, dob, address) values (3, 'Putnam', 'Offord', 2.39, '2023-04-30', 'Żyrardów');
insert into student (id, first_name, last_name, gpa, dob, address) values (4, 'Sydel', 'Delgua', 4.77, '2022-08-31', 'Pāvilosta');
insert into student (id, first_name, last_name, gpa, dob, address) values (5, 'Mame', 'Burdell', 1.63, '2022-12-25', 'Sŭedinenie');
insert into student (id, first_name, last_name, gpa, dob, address) values (6, 'Jarret', 'Duferie', 4.01, '2023-08-07', 'Baorixile');
insert into student (id, first_name, last_name, gpa, dob, address) values (7, 'Manon', 'Whylie', 1.85, '2023-07-03', 'Vyaz’ma');
insert into student (id, first_name, last_name, gpa, dob, address) values (8, 'Zaneta', 'Sprigging', 1.68, '2023-03-19', 'Igarra');
insert into student (id, first_name, last_name, gpa, dob, address) values (9, 'Kathye', 'Pesic', 2.76, '2022-08-19', 'Alvito de São Pedro');
insert into student (id, first_name, last_name, gpa, dob, address) values (10, 'Ana', 'McCourtie', 3.06, '2023-06-06', 'La Peña');
insert into student (id, first_name, last_name, gpa, dob, address) values (11, 'Monroe', 'Buzine', 3.66, '2023-05-25', 'Kinango');
insert into student (id, first_name, last_name, gpa, dob, address) values (12, 'Elsey', 'Drydale', 4.38, '2022-10-07', 'Subusub');
insert into student (id, first_name, last_name, gpa, dob, address) values (13, 'Lennie', 'Constance', 2.23, '2023-05-29', 'Sarāb');
insert into student (id, first_name, last_name, gpa, dob, address) values (14, 'Leland', 'Hubber', 4.21, '2023-04-05', '‘Arīshah');
insert into student (id, first_name, last_name, gpa, dob, address) values (15, 'Jaquith', 'Mayor', 1.26, '2023-04-07', 'Hele');
insert into student (id, first_name, last_name, gpa, dob, address) values (16, 'Janey', 'Gask', 1.37, '2023-05-12', 'Springfield');
insert into student (id, first_name, last_name, gpa, dob, address) values (17, 'Roanne', 'Messiter', 1.56, '2023-06-09', 'Fengjiang');
insert into student (id, first_name, last_name, gpa, dob, address) values (18, 'Sterne', 'Darrow', 3.51, '2023-05-27', 'Al Ḩaffah');
insert into student (id, first_name, last_name, gpa, dob, address) values (19, 'Wilfred', 'Hebborn', 2.98, '2023-01-03', 'Matsena');
insert into student (id, first_name, last_name, gpa, dob, address) values (20, 'Rosina', 'Burnel', 4.95, '2022-09-26', 'Gaozhuang');
insert into student (id, first_name, last_name, gpa, dob, address) values (21, 'Giuditta', 'Deeks', 2.04, '2022-10-03', 'Cruz');
insert into student (id, first_name, last_name, gpa, dob, address) values (22, 'Currey', 'Seekings', 4.27, '2023-05-08', 'Manikchari');
insert into student (id, first_name, last_name, gpa, dob, address) values (23, 'Queenie', 'Bravey', 2.15, '2023-08-03', 'Chanthaburi');
insert into student (id, first_name, last_name, gpa, dob, address) values (24, 'Pauly', 'Kirkpatrick', 2.43, '2023-04-24', 'Yuyue');
insert into student (id, first_name, last_name, gpa, dob, address) values (25, 'Balduin', 'Van Rembrandt', 3.13, '2022-08-23', 'Kostel');
insert into student (id, first_name, last_name, gpa, dob, address) values (26, 'Padraig', 'Kliemchen', 2.55, '2022-09-09', 'Makubetsu');
insert into student (id, first_name, last_name, gpa, dob, address) values (27, 'Laura', 'Donett', 4.92, '2022-09-09', 'Uppsala');
insert into student (id, first_name, last_name, gpa, dob, address) values (28, 'Filmer', 'Dolbey', 4.99, '2023-01-23', 'Nha Trang');
insert into student (id, first_name, last_name, gpa, dob, address) values (29, 'Danna', 'Bultitude', 1.77, '2023-01-27', 'K’anak’erravan');
insert into student (id, first_name, last_name, gpa, dob, address) values (30, 'Antonina', 'MacCulloch', 1.99, '2023-02-09', 'Jiumen');
insert into student (id, first_name, last_name, gpa, dob, address) values (31, 'Bebe', 'Yearnes', 4.25, '2023-08-16', 'Al Farwānīyah');
insert into student (id, first_name, last_name, gpa, dob, address) values (32, 'Lonny', 'Bearcroft', 2.68, '2023-08-05', 'Cholpon-Ata');
insert into student (id, first_name, last_name, gpa, dob, address) values (33, 'Coop', 'Elham', 4.43, '2022-10-09', 'Mehtar Lām');
insert into student (id, first_name, last_name, gpa, dob, address) values (34, 'Angie', 'Matchitt', 3.64, '2023-02-13', 'Soweto');
insert into student (id, first_name, last_name, gpa, dob, address) values (35, 'Winn', 'Staneland', 1.89, '2022-12-13', 'Lubenec');
insert into student (id, first_name, last_name, gpa, dob, address) values (36, 'Joceline', 'Botterell', 3.22, '2023-01-24', 'Lipci');
insert into student (id, first_name, last_name, gpa, dob, address) values (37, 'Clementine', 'Hartford', 4.13, '2022-09-15', 'Georgiyevsk');
insert into student (id, first_name, last_name, gpa, dob, address) values (38, 'Blane', 'Shrieve', 1.8, '2023-06-26', 'Dalonghua');
insert into student (id, first_name, last_name, gpa, dob, address) values (39, 'Brod', 'Rattery', 3.56, '2023-01-03', 'Tân Sơn');
insert into student (id, first_name, last_name, gpa, dob, address) values (40, 'Maryanne', 'Saipy', 3.85, '2023-07-08', 'Narutō');
insert into student (id, first_name, last_name, gpa, dob, address) values (41, 'Gwyneth', 'Groundwater', 4.63, '2023-02-28', 'Krasne');
insert into student (id, first_name, last_name, gpa, dob, address) values (42, 'Tersina', 'McVie', 2.52, '2023-01-08', 'Erbil');
insert into student (id, first_name, last_name, gpa, dob, address) values (43, 'Hagen', 'Jozsef', 3.09, '2023-04-13', 'Andrijaševci');
insert into student (id, first_name, last_name, gpa, dob, address) values (44, 'Turner', 'Pybus', 4.22, '2023-07-26', 'Ikšķile');
insert into student (id, first_name, last_name, gpa, dob, address) values (45, 'Zoe', 'Wyldbore', 1.88, '2023-02-08', 'Foros do Trapo');
insert into student (id, first_name, last_name, gpa, dob, address) values (46, 'Betti', 'Thorn', 3.03, '2022-12-11', 'Bitin');
insert into student (id, first_name, last_name, gpa, dob, address) values (47, 'Benson', 'Allon', 1.12, '2022-09-08', 'Yunluo');
insert into student (id, first_name, last_name, gpa, dob, address) values (48, 'Neil', 'Bartolomeo', 1.55, '2023-06-26', 'Niedzica');
insert into student (id, first_name, last_name, gpa, dob, address) values (49, 'Sherm', 'Maymand', 3.98, '2023-03-25', 'Itapecuru Mirim');
insert into student (id, first_name, last_name, gpa, dob, address) values (50, 'Jacobo', 'Gregoratti', 2.93, '2022-11-25', 'Zhujiatai');
insert into student (id, first_name, last_name, gpa, dob, address) values (51, 'Leila', 'Ribbens', 3.52, '2023-01-23', 'Löddeköpinge');
insert into student (id, first_name, last_name, gpa, dob, address) values (52, 'Robbyn', 'Kwiek', 1.83, '2023-02-23', 'Cerro');
insert into student (id, first_name, last_name, gpa, dob, address) values (53, 'Rowe', 'Aysik', 3.74, '2022-09-20', 'Glagahan');
insert into student (id, first_name, last_name, gpa, dob, address) values (54, 'Carlita', 'Matsell', 2.51, '2023-07-12', 'Bonneuil-sur-Marne');
insert into student (id, first_name, last_name, gpa, dob, address) values (55, 'Ree', 'Bownass', 2.41, '2023-01-30', 'Laojun');
insert into student (id, first_name, last_name, gpa, dob, address) values (56, 'Zorah', 'Birchner', 3.42, '2023-04-15', 'Mangaratiba');
insert into student (id, first_name, last_name, gpa, dob, address) values (57, 'Westleigh', 'Speenden', 3.75, '2023-07-11', 'Jokkmokk');
insert into student (id, first_name, last_name, gpa, dob, address) values (58, 'Renell', 'De Banke', 3.05, '2023-07-03', 'Luokou');
insert into student (id, first_name, last_name, gpa, dob, address) values (59, 'August', 'Downing', 3.3, '2022-11-09', 'Banqiao');
insert into student (id, first_name, last_name, gpa, dob, address) values (60, 'Allianora', 'Silmon', 2.37, '2022-12-31', 'Higuerote');
insert into student (id, first_name, last_name, gpa, dob, address) values (61, 'Tim', 'Dikels', 1.81, '2023-03-28', 'Hadakewa');
insert into student (id, first_name, last_name, gpa, dob, address) values (62, 'Janith', 'Loudiane', 3.11, '2022-12-18', 'Lindome');
insert into student (id, first_name, last_name, gpa, dob, address) values (63, 'Chaddy', 'Tumber', 4.1, '2022-11-25', 'Wingham');
insert into student (id, first_name, last_name, gpa, dob, address) values (64, 'Mike', 'O''Hannigan', 2.65, '2022-10-29', 'Strassen');
insert into student (id, first_name, last_name, gpa, dob, address) values (65, 'Roseanna', 'Flanders', 3.14, '2022-09-22', 'Denver');
insert into student (id, first_name, last_name, gpa, dob, address) values (66, 'Valentine', 'Zincke', 1.85, '2022-10-29', 'Libao');
insert into student (id, first_name, last_name, gpa, dob, address) values (67, 'Una', 'Wilcockes', 2.4, '2023-03-10', 'Bronnitsy');
insert into student (id, first_name, last_name, gpa, dob, address) values (68, 'Jodie', 'Templeton', 2.1, '2022-09-08', 'Poyang');
insert into student (id, first_name, last_name, gpa, dob, address) values (69, 'Tilly', 'Veljes', 2.68, '2022-10-10', 'Yimamu');
insert into student (id, first_name, last_name, gpa, dob, address) values (70, 'Luisa', 'Vasyunin', 1.57, '2023-05-31', 'La Soledad');
insert into student (id, first_name, last_name, gpa, dob, address) values (71, 'Chery', 'Hearnaman', 2.51, '2023-03-11', 'Dazhigu');
insert into student (id, first_name, last_name, gpa, dob, address) values (72, 'Tiebout', 'Connechie', 2.46, '2023-01-06', 'Tarrafal');
insert into student (id, first_name, last_name, gpa, dob, address) values (73, 'Deena', 'Sholl', 3.75, '2023-04-28', 'Ceres');
insert into student (id, first_name, last_name, gpa, dob, address) values (74, 'Padgett', 'Mackerness', 4.61, '2022-09-19', 'Loacan');
insert into student (id, first_name, last_name, gpa, dob, address) values (75, 'Yancy', 'Maisey', 2.49, '2023-01-29', 'Divisoria');
insert into student (id, first_name, last_name, gpa, dob, address) values (76, 'Reece', 'Gilliland', 1.05, '2023-04-08', 'Srunikrajan');
insert into student (id, first_name, last_name, gpa, dob, address) values (77, 'Rodney', 'Corsar', 1.26, '2022-10-09', 'Zhoukou');
insert into student (id, first_name, last_name, gpa, dob, address) values (78, 'Gabrielle', 'Cellier', 4.59, '2023-04-30', 'Candi Prambanan');
insert into student (id, first_name, last_name, gpa, dob, address) values (79, 'Sloane', 'Woolacott', 3.14, '2022-09-09', 'Batiovo');
insert into student (id, first_name, last_name, gpa, dob, address) values (80, 'Lambert', 'Fumagallo', 3.55, '2023-06-27', 'Honiara');
insert into student (id, first_name, last_name, gpa, dob, address) values (81, 'Dav', 'Gislebert', 4.42, '2023-03-12', 'Gonça');
insert into student (id, first_name, last_name, gpa, dob, address) values (82, 'Oralia', 'Lauder', 1.36, '2023-02-20', 'Caramay');
insert into student (id, first_name, last_name, gpa, dob, address) values (83, 'Roger', 'Tivenan', 2.01, '2023-03-11', 'Kanoni');
insert into student (id, first_name, last_name, gpa, dob, address) values (84, 'Etti', 'Narup', 2.8, '2023-07-25', 'Urzhar');
insert into student (id, first_name, last_name, gpa, dob, address) values (85, 'Duncan', 'Pitman', 2.78, '2023-02-19', 'Teluksantong');
insert into student (id, first_name, last_name, gpa, dob, address) values (86, 'Vonnie', 'Cyphus', 2.28, '2023-04-18', 'Liběšice');
insert into student (id, first_name, last_name, gpa, dob, address) values (87, 'Zia', 'Dahlbom', 1.98, '2022-10-25', 'Jindong');
insert into student (id, first_name, last_name, gpa, dob, address) values (88, 'Josee', 'Tott', 3.73, '2023-03-28', 'Jeseník');
insert into student (id, first_name, last_name, gpa, dob, address) values (89, 'Lindy', 'Makin', 1.66, '2022-09-12', 'Dundbürd');
insert into student (id, first_name, last_name, gpa, dob, address) values (90, 'Kellyann', 'Banister', 3.99, '2023-01-04', 'Samangawah');
insert into student (id, first_name, last_name, gpa, dob, address) values (91, 'Tasha', 'Manger', 2.86, '2023-04-27', 'San José');
insert into student (id, first_name, last_name, gpa, dob, address) values (92, 'Elissa', 'Wythe', 2.68, '2023-05-20', 'Leśna Podlaska');
insert into student (id, first_name, last_name, gpa, dob, address) values (93, 'Gwyneth', 'Dykes', 3.3, '2023-03-05', 'Chadian');
insert into student (id, first_name, last_name, gpa, dob, address) values (94, 'Sigismond', 'Cunniff', 2.78, '2023-01-12', 'Zelenchukskaya');
insert into student (id, first_name, last_name, gpa, dob, address) values (95, 'Debera', 'Osgodby', 3.57, '2023-06-26', 'San Benito');
insert into student (id, first_name, last_name, gpa, dob, address) values (96, 'Alain', 'Arens', 3.3, '2023-03-11', 'Karang');
insert into student (id, first_name, last_name, gpa, dob, address) values (97, 'Justis', 'McKimmey', 2.75, '2022-09-12', 'Sherpur');
insert into student (id, first_name, last_name, gpa, dob, address) values (98, 'Josephina', 'Ledford', 3.77, '2022-09-09', 'Ḩukūmat-e Shīnkaī');
insert into student (id, first_name, last_name, gpa, dob, address) values (99, 'Garret', 'Dallman', 4.49, '2023-04-02', 'Várzea Paulista');
insert into student (id, first_name, last_name, gpa, dob, address) values (100, 'Lennie', 'Stilldale', 3.96, '2023-04-15', 'Vidnoye');